# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.DateTimeField(auto_created=True)),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('location', models.CharField(max_length=100)),
                ('name_area', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather1', models.IntegerField()),
                ('weather2', models.IntegerField()),
                ('weather3', models.IntegerField()),
                ('weather4', models.IntegerField()),
                ('weather5', models.IntegerField()),
            ],
        ),
    ]
