# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20170722_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathertag',
            name='cloudy',
        ),
        migrations.RemoveField(
            model_name='weathertag',
            name='foggy',
        ),
        migrations.RemoveField(
            model_name='weathertag',
            name='rainy',
        ),
        migrations.RemoveField(
            model_name='weathertag',
            name='snowy',
        ),
        migrations.RemoveField(
            model_name='weathertag',
            name='sunny',
        ),
        migrations.AddField(
            model_name='weathertag',
            name='tag_weather',
            field=models.CharField(choices=[('sunny', '맑음'), ('cloudy', '흐림'), ('rainy', '비'), ('snowy', '눈'), ('foggy', '안개')], default='sunny', max_length=2),
        ),
    ]
