# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20170722_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathertag',
            name='cloudy',
            field=models.IntegerField(default=0, verbose_name='흐림'),
        ),
        migrations.AddField(
            model_name='weathertag',
            name='foggy',
            field=models.IntegerField(default=0, verbose_name='안개'),
        ),
        migrations.AddField(
            model_name='weathertag',
            name='rainy',
            field=models.IntegerField(default=0, verbose_name='비'),
        ),
        migrations.AddField(
            model_name='weathertag',
            name='snowy',
            field=models.IntegerField(default=0, verbose_name='눈'),
        ),
        migrations.AddField(
            model_name='weathertag',
            name='sunny',
            field=models.IntegerField(default=0, verbose_name='맑음'),
        ),
    ]
