branch-defaults:
  default:
    environment: weatherpractice-dev
    group_suffix: null
global:
  application_name: weatherpractice
  branch: null
  default_ec2_keyname: AWSEC2-hwangseonjeong
  default_platform: Docker 1.12.6
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
