# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
    ]
