# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_music', models.ImageField(blank=True, upload_to='img_music')),
                ('name_music', models.CharField(max_length=100)),
                ('name_singer', models.CharField(max_length=100)),
                ('file_music', models.FileField(upload_to='music')),
                ('name_album', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.DateTimeField(auto_created=True)),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('location', models.CharField(max_length=100)),
                ('name_area', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunny', models.IntegerField(default=0, verbose_name='맑음')),
                ('foggy', models.IntegerField(default=0, verbose_name='안개')),
                ('rainy', models.IntegerField(default=0, verbose_name='비')),
                ('cloudy', models.IntegerField(default=0, verbose_name='흐림')),
                ('snowy', models.IntegerField(default=0, verbose_name='눈')),
                ('tag_music', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.Music')),
                ('tag_weather', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.Weather')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='tag_weather',
            field=models.ManyToManyField(choices=[('sunny', '맑음'), ('cloudy', '흐림'), ('rainy', '비'), ('snowy', '눈'), ('foggy', '안개')], related_name='_music_tag_weather_+', through='music.WeatherTag', to='music.Weather'),
        ),
        migrations.AlterUniqueTogether(
            name='weathertag',
            unique_together=set([('tag_music', 'tag_weather')]),
        ),
    ]
