# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_music', models.CharField(max_length=100)),
                ('name_singer', models.CharField(max_length=100)),
                ('file_music', models.FileField(upload_to='')),
                ('name_album', models.CharField(max_length=100)),
                ('date_released', models.DateField(auto_now_add=True)),
                ('tag_weather', models.CharField(max_length=1000)),
                ('name_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
