# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathertag',
            name='cloudy',
            field=models.IntegerField(default=1, verbose_name='흐림'),
        ),
        migrations.AlterField(
            model_name='weathertag',
            name='foggy',
            field=models.IntegerField(default=1, verbose_name='안개'),
        ),
        migrations.AlterField(
            model_name='weathertag',
            name='rainy',
            field=models.IntegerField(default=1, verbose_name='비'),
        ),
        migrations.AlterField(
            model_name='weathertag',
            name='snowy',
            field=models.IntegerField(default=1, verbose_name='눈'),
        ),
        migrations.AlterField(
            model_name='weathertag',
            name='sunny',
            field=models.IntegerField(default=1, verbose_name='맑음'),
        ),
    ]
