# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='tag_weather',
            field=models.ForeignKey(choices=[('sunny', '맑음'), ('cloudy', '흐림'), ('rainy', '비'), ('snowy', '눈'), ('foggy', '안개')], on_delete=django.db.models.deletion.PROTECT, to='weather.WeatherTag'),
        ),
    ]
