# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='name_area',
            new_name='cur_weather',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='time_range',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='weather',
        ),
        migrations.AddField(
            model_name='weather',
            name='time_saved',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
