# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170725_2201'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weathertag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='weathertag',
            name='tag_music',
        ),
        migrations.RemoveField(
            model_name='weathertag',
            name='tag_weather',
        ),
        migrations.RemoveField(
            model_name='music',
            name='tag_weather',
        ),
        migrations.AddField(
            model_name='music',
            name='cloudy',
            field=models.IntegerField(default=1, verbose_name='흐림'),
        ),
        migrations.AddField(
            model_name='music',
            name='foggy',
            field=models.IntegerField(default=1, verbose_name='안개'),
        ),
        migrations.AddField(
            model_name='music',
            name='rainy',
            field=models.IntegerField(default=1, verbose_name='비'),
        ),
        migrations.AddField(
            model_name='music',
            name='snowy',
            field=models.IntegerField(default=1, verbose_name='눈'),
        ),
        migrations.AddField(
            model_name='music',
            name='sunny',
            field=models.IntegerField(default=1, verbose_name='맑음'),
        ),
        migrations.DeleteModel(
            name='WeatherTag',
        ),
    ]
