# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170726_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cloudy',
            field=models.PositiveIntegerField(default=1, verbose_name='흐림'),
        ),
        migrations.AlterField(
            model_name='music',
            name='foggy',
            field=models.PositiveIntegerField(default=1, verbose_name='안개'),
        ),
        migrations.AlterField(
            model_name='music',
            name='rainy',
            field=models.PositiveIntegerField(default=1, verbose_name='비'),
        ),
        migrations.AlterField(
            model_name='music',
            name='snowy',
            field=models.PositiveIntegerField(default=1, verbose_name='눈'),
        ),
        migrations.AlterField(
            model_name='music',
            name='sunny',
            field=models.PositiveIntegerField(default=1, verbose_name='맑음'),
        ),
    ]
