# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170722_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='tag_weather',
            field=models.CharField(choices=[('sunny', '맑음'), ('cloudy', '흐림'), ('rainy', '비'), ('snowy', '눈'), ('foggy', '안개')], max_length=100),
        ),
    ]
