# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170722_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='date_created',
        ),
    ]
